### ISSUE TITLE
Service Layer and Pagination

### ISSUE THREAD

**Issue by marcojulian** [fgallo94/ShopWallet#1]
I see no relationship between the entities item and category.
You may want to add a @RequestMapping for CategoryController.
Add  a service layer between the controller layer and the repository layer.
You can also add pagination for the ItemsController class ... here is a link with a simple explanation of how to do it : https://www.baeldung.com/rest-api-pagination-in-spring

**Comment by fgallo94** [comment]
Thanks for the issue report Julian, I'll try to fix this on "fixes-1" branch already I fixed the layer and relationship problem but I need to add pagination to the ItemController.
If you want, you can start to watch this repository to know when all the features is pushed.

**Comment by fgallo94** [comment]
Added pagination on the last commit on master.
